version: "3"

networks:
  ethereum:

services:
  lodestar-beacon:
    image: ${image:-0labs/lodestar:latest}
    container_name: lodestar-beacon
    command:
      - "lodestar"
      - "beacon"
    environment:
      CONF_DIR: ${CONF_DIR:-/etc/lodestar}
    env_file:
      - ${beacon_env_vars:-.beacon.env}
    ports:
      - ${p2p_tcp_port:-9000}:9000/tcp
      - ${p2p_udp_port:-9000}:9000/udp
      - ${beacon_api_port:-9596}:9596/tcp
      - ${beacon_metrics_port:-8008}:8008/tcp
    volumes:
      - "${host_root_dir:-/var/tmp/lodestar}:${CONFIG_rootDir:-/root/.local/share/lodestar}"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}

  lodestar-validator:
    image: ${image:-0labs/lodestar:latest}
    container_name: lodestar-validator
    command:
      - "lodestar"
      - "validator"
    env_file:
      - ${validator_env_vars:-.validator.env}
    volumes:
      - "${host_root_dir:-/var/tmp/lodestar}:${CONFIG_rootDir:-/root/.local/share/lodestar/}"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}
